#!/usr/bin/env python3
"""Thermal and electrical budget for the boiler and mains circuit.

Reads cad/design_params.scad (via scripts/design_params.py) and computes:
  - heater current vs the mains breaker, with the 80 percent margin rule
  - copper boiler mass from the shell dimensions
  - heat-up time from ambient to brew temperature

Writes outputs/budgets/energy_budget.md (deterministic, no timestamps).
Lines flagged [!] are budget violations; --check exits non-zero on any.

Expected order of magnitude, stated before running (per the working
rules): 1.0 l + ~1.2 kg copper at 1400 W is roughly 340 kJ, about 4 min.
If the computed value disagrees wildly, suspect the model, not the check.
"""

import argparse
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "scripts"))
from design_params import PARAMS  # noqa: E402

AMBIENT_C = 20.0
WATER_C_J_KG_K = 4186.0
COPPER_C_J_KG_K = 385.0
COPPER_RHO_KG_M3 = 8960.0
BREAKER_CONTINUOUS_FRACTION = 0.8
MAX_HEATUP_S = 360.0

OUT = Path(__file__).resolve().parent.parent / "outputs" / "budgets" / "energy_budget.md"


def copper_mass_kg() -> float:
    od = PARAMS["boiler_od"] / 1000.0
    h = PARAMS["boiler_h"] / 1000.0
    wall = PARAMS["boiler_wall"] / 1000.0
    shell = math.pi * od * h * wall
    caps = 2 * math.pi * (od / 2) ** 2 * wall
    return (shell + caps) * COPPER_RHO_KG_M3


def budget() -> tuple[list[str], int]:
    p = PARAMS
    current_a = p["heater_power_w"] / p["mains_voltage"]
    breaker_limit_a = p["mains_breaker_a"] * BREAKER_CONTINUOUS_FRACTION
    m_cu = copper_mass_kg()
    m_water = p["boiler_volume_l"]  # 1 l of water is 1 kg
    dt = p["brew_temp_c"] - AMBIENT_C
    energy_j = (m_water * WATER_C_J_KG_K + m_cu * COPPER_C_J_KG_K) * dt
    heatup_s = energy_j / p["heater_power_w"]

    flags = 0
    lines = [
        "# Energy budget",
        "",
        "Generated by tools/energy_budget.py from cad/design_params.scad.",
        "Regenerate with scripts/regen_all.py, never edit by hand.",
        "",
        "## Electrical",
        "",
        f"- heater power: {p['heater_power_w']} W at {p['mains_voltage']} V",
        f"- heater current: {current_a:.2f} A",
        f"- breaker: {p['mains_breaker_a']} A, continuous limit "
        f"{breaker_limit_a:.1f} A ({BREAKER_CONTINUOUS_FRACTION:.0%})",
    ]
    if current_a > breaker_limit_a:
        lines.append(f"- [!] heater current {current_a:.2f} A exceeds the "
                     f"continuous limit {breaker_limit_a:.1f} A")
        flags += 1
    else:
        lines.append(f"- margin to continuous limit: "
                     f"{breaker_limit_a - current_a:.2f} A")

    lines += [
        "",
        "## Thermal",
        "",
        f"- boiler fill: {m_water:.2f} kg water, shell {m_cu:.2f} kg copper",
        f"- ambient {AMBIENT_C:.0f} C to brew {p['brew_temp_c']} C: "
        f"{energy_j / 1000:.0f} kJ",
        f"- heat-up at {p['heater_power_w']} W: {heatup_s / 60:.1f} min",
    ]
    if heatup_s > MAX_HEATUP_S:
        lines.append(f"- [!] heat-up {heatup_s:.0f} s exceeds the "
                     f"{MAX_HEATUP_S:.0f} s budget")
        flags += 1
    else:
        lines.append(f"- margin to the {MAX_HEATUP_S / 60:.0f} min budget: "
                     f"{(MAX_HEATUP_S - heatup_s) / 60:.1f} min")
    lines.append("")
    return lines, flags


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="print only, exit non-zero on any [!] flag")
    ap.add_argument("--out", type=Path, default=OUT,
                    help="output file (default outputs/budgets/energy_budget.md)")
    args = ap.parse_args()

    lines, flags = budget()
    text = "\n".join(lines)
    print(text)
    if args.check:
        return 1 if flags else 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
